In [1]:
import numpy
numpy.random.seed(1337)
from numpy import loadtxt
from keras.models import Sequential
from keras.layers import Dense

In [2]:
dataset=loadtxt('Fitness_Tracker 1.csv', delimiter=',')

In [3]:
x=dataset[:,0:10]
y=dataset[:,-1]
print(x,y)
n=x.shape[0]
print(n)

[[4.0000e+00 9.9900e+03 3.5000e+02 ... 1.4000e+02 1.1400e+02 6.0000e+00]
 [3.0000e+00 9.9800e+03 3.0000e+02 ... 1.2000e+02 1.1700e+02 6.0000e+00]
 [2.0000e+00 9.9700e+03 2.5000e+02 ... 1.0000e+02 1.2000e+02 5.0000e+00]
 ...
 [8.0000e+00 1.0664e+04 6.6400e+02 ... 1.8600e+02 9.4000e+01 9.0000e+00]
 [8.0000e+00 1.0665e+04 6.6500e+02 ... 1.8600e+02 9.4000e+01 9.0000e+00]
 [8.0000e+00 1.0666e+04 6.6600e+02 ... 1.8600e+02 9.4000e+01 9.0000e+00]] [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.

In [4]:
ran=numpy.arange(n)
numpy.random.shuffle(ran)
x=x[ran]
y=y[ran]
print(x,y)

[[6.0000e+00 1.0340e+04 7.0000e+02 ... 1.6600e+02 9.7000e+01 8.0000e+00]
 [7.0000e+00 1.0490e+04 6.0000e+02 ... 1.7500e+02 1.0700e+02 8.0000e+00]
 [8.0000e+00 1.0613e+04 6.1300e+02 ... 1.8100e+02 9.9000e+01 9.0000e+00]
 ...
 [8.0000e+00 1.0515e+04 5.1500e+02 ... 1.7100e+02 1.0900e+02 8.0000e+00]
 [7.0000e+00 1.0410e+04 6.0000e+02 ... 1.7500e+02 1.0700e+02 8.0000e+00]
 [7.0000e+00 1.0030e+04 4.3000e+02 ... 1.7100e+02 1.1000e+02 8.0000e+00]] [1. 1. 1. 0. 1. 1. 0. 1. 1. 1. 1. 1. 0. 1. 1. 0. 0. 0. 1. 1. 0. 0. 0. 1.
 1. 1. 1. 0. 0. 1. 0. 1. 0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 1. 1. 0. 1. 0.
 1. 1. 0. 0. 0. 0. 1. 0. 1. 0. 1. 1. 0. 1. 1. 0. 1. 1. 0. 0. 1. 0. 1. 1.
 1. 1. 1. 0. 1. 1. 0. 0. 0. 0. 0. 1. 1. 0. 1. 1. 0. 1. 0. 0. 1. 1. 1. 0.
 0. 1. 0. 0. 1. 0. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 1. 1. 1. 0. 0. 0. 0. 1. 1. 1. 0. 1. 0. 1. 0. 1. 0. 0. 0. 1. 1. 0. 1.
 1. 0. 1. 0. 0. 0. 0. 1. 1. 1. 1. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 1. 0. 0.
 1. 0. 0. 1. 1. 1. 0. 1. 1. 1. 1. 0. 1. 1. 1.

In [5]:
split=round(n*2/3)
x_train=x[:split]
y_train=y[:split]
x_test=x[split:]
y_test=y[split:]
print(x_train,y_train,x_test,y_test)

[[6.0000e+00 1.0340e+04 7.0000e+02 ... 1.6600e+02 9.7000e+01 8.0000e+00]
 [7.0000e+00 1.0490e+04 6.0000e+02 ... 1.7500e+02 1.0700e+02 8.0000e+00]
 [8.0000e+00 1.0613e+04 6.1300e+02 ... 1.8100e+02 9.9000e+01 9.0000e+00]
 ...
 [3.0000e+00 9.9500e+03 1.5000e+02 ... 6.0000e+01 1.2600e+02 4.0000e+00]
 [8.0000e+00 1.0539e+04 5.3900e+02 ... 1.7400e+02 1.0700e+02 8.0000e+00]
 [3.0000e+00 9.8650e+03 3.8000e+02 ... 1.5700e+02 1.1300e+02 6.0000e+00]] [1. 1. 1. 0. 1. 1. 0. 1. 1. 1. 1. 1. 0. 1. 1. 0. 0. 0. 1. 1. 0. 0. 0. 1.
 1. 1. 1. 0. 0. 1. 0. 1. 0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 1. 1. 0. 1. 0.
 1. 1. 0. 0. 0. 0. 1. 0. 1. 0. 1. 1. 0. 1. 1. 0. 1. 1. 0. 0. 1. 0. 1. 1.
 1. 1. 1. 0. 1. 1. 0. 0. 0. 0. 0. 1. 1. 0. 1. 1. 0. 1. 0. 0. 1. 1. 1. 0.
 0. 1. 0. 0. 1. 0. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 1. 1. 1. 0. 0. 0. 0. 1. 1. 1. 0. 1. 0. 1. 0. 1. 0. 0. 0. 1. 1. 0. 1.
 1. 0. 1. 0. 0. 0. 0. 1. 1. 1. 1. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 1. 0. 0.
 1. 0. 0. 1. 1. 1. 0. 1. 1. 1. 1. 0. 1. 1. 1.

In [6]:
model=Sequential()
model.add(Dense(512, input_dim=10,activation='sigmoid'))
model.add(Dense(512,activation='sigmoid'))
model.add(Dense(512,activation='sigmoid'))
model.add(Dense(1,activation='softmax'))

In [7]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [8]:
history=model.fit(x_train,y_train,batch_size=2,epochs=80,validation_data=(x_test,y_test),verbose=1)

Epoch 1/80
167/167 [==============================] - 3s 16ms/step - loss: 0.0000e+00 - accuracy: 0.5495 - val_loss: 0.0000e+00 - val_accuracy: 0.5629
Epoch 2/80
167/167 [==============================] - 2s 14ms/step - loss: 0.0000e+00 - accuracy: 0.5495 - val_loss: 0.0000e+00 - val_accuracy: 0.5629
Epoch 3/80
167/167 [==============================] - 2s 14ms/step - loss: 0.0000e+00 - accuracy: 0.5495 - val_loss: 0.0000e+00 - val_accuracy: 0.5629
Epoch 4/80
167/167 [==============================] - 2s 14ms/step - loss: 0.0000e+00 - accuracy: 0.5495 - val_loss: 0.0000e+00 - val_accuracy: 0.5629ss: 0.0000e+00 - accura
Epoch 5/80
167/167 [==============================] - 2s 14ms/step - loss: 0.0000e+00 - accuracy: 0.5495 - val_loss: 0.0000e+00 - val_accuracy: 0.5629
Epoch 6/80
167/167 [==============================] - 2s 13ms/step - loss: 0.0000e+00 - accuracy: 0.5495 - val_loss: 0.0000e+00 - val_accuracy: 0.5629
Epoch 7/80
167/167 [==============================] - 2s 13ms/step - lo

In [9]:
accuracy=model.evaluate(x,y)

16/16 [==============================] - 0s 8ms/step - loss: 0.0000e+00 - accuracy: 0.5540


In [10]:
prediction=model.predict_classes(x)

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


In [11]:
print(x[4],prediction[4],y[4])

[6.000e+00 1.049e+04 6.500e+02 9.200e+01 9.200e+01 2.600e+01 9.400e+01
 1.690e+02 1.060e+02 8.000e+00] [1] 1.0
